FROM openjdk:17
EXPOSE 8080
ADD target/kubernetes-spring-boot-app-0.0.1-SNAPSHOT.jar  kubernetes-spring-boot-app-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","jar","/kubernetes-spring-boot-app-0.0.1-SNAPSHOT.jar"]